name: Build Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
 - name: Build with Gradle
        working-directory: project
        run: |
          ls -la
          ls -la */
          chmod +x gradlew
          ./gradlew build
